"""Added Role column to User table

Revision ID: 7362c67f8f7a
Revises: 
Create Date: 2024-10-03 23:36:41.265202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7362c67f8f7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.add_column('users', sa.Column('user_role', sa.String(), nullable=False,server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    op.create_table('accounts',
    sa.Column('acc_id', sa.INTEGER(), server_default=sa.text("nextval('accounts_acc_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acc_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('acc_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('acc_balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='accounts_user_id_fkey'),
    sa.PrimaryKeyConstraint('acc_id', name='accounts_pkey'),
    sa.UniqueConstraint('acc_number', name='accounts_acc_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senders_acc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receivers_acc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receivers_acc_id'], ['accounts.acc_id'], name='transactions_receivers_acc_id_fkey'),
    sa.ForeignKeyConstraint(['senders_acc_id'], ['accounts.acc_id'], name='transactions_senders_acc_id_fkey'),
    sa.PrimaryKeyConstraint('transaction_id', name='transactions_pkey')
    )
    op.create_table('loan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='loan_pkey')
    )
    # ### end Alembic commands ###
